### ISSUE TITLE
Doesn't reload while Chrome is not focused

### ISSUE THREAD

**Issue by cespare** [MikeRogers0/LivePage#31]
I have an editor and chrome open. When I make a change in the editor and save, nothing happens until I alt-tab back over to chrome. Then the change instantly takes effect.

Maybe Chrome doesn't let the background JS run while out of focus or something?

This is Chrome 38 beta.

**Comment by feedthebayer** [comment]
Any update on this?

**Comment by MikeRogers0** [comment]
https://github.com/MikeRogers0/LivePage/tree/reloadCssInOrginalPlace - I think I've found a fix and put it in here - though I've not had any time finish / publish the update :/

**Comment by papa-gene** [comment]
Hi MikeRogers0! I am still experiencing this issue. To be precise, HTML reloads just fine when out of focus, but for CSS, I have to drag the mouse over Chrome window (I believe OSX does "Focus follows mouse"). This is on Chrome 44.0.2403.89 for OSX, with the latest version of the plugin (1.6.0). Let me know if you need more info.
Great extension otherwise!

**Comment by MikeRogers0** [comment]
I'm closing this issue. While testing the most recent release I was unable to recreate this issue, though I think chrome will try to save CPU/GPU cycles where possible.

In either case, without doing a hard refresh every once in a while I can't see a good fix this to.
