### ISSUE TITLE
Refresh resets scroll location to top

### ISSUE THREAD

**Issue by arechsteiner** [MikeRogers0/LivePage#50]
I'm using LivePage to auto-refresh a site that has a greater height than my viewport. When I'm scrolled all the way to the bottom (say I'm working on the footer), and I make a change, the auto-refresh often leaves me at the very top of the page. 

This does not happen all the time. But I can reproduce it fairly good by modifying the padding of an element. If I modify the color of the same element though, it *never* happens. This makes me think it could be a problem related to the changing document height.

**Comment by MikeRogers0** [comment]
This is most likely happening because the page is being drawn by the browser (In a few microseconds it goes from old styles > no styles > new styles). 

Though I can imagine how this would be annoying, I try and find a fix to restore the page scroll position upon redrawing/reloading the page this weekend :)

**Comment by MikeRogers0** [comment]
This is now in master, I'm going to aim to get this released to the chrome store by tomorrow morning :)

**Comment by arechsteiner** [comment]
Works great now! Thank you very much.
